### Cadastrar project
POST https://localhost:5001/api/project/create
Content-Type: application/json

{
    "Name" : "Project 1",
    "User" : "Maria",
    "Company" : "Tenda",
    "StartDate" : "2021-09-30",
    "EndDate" : "2021-10-30"
}


### Listar project
GET https://localhost:5001/api/project/list

### Buscar project pelo id
GET https://localhost:5001/api/project/getbyid/6

### Buscar project pelo id
GET https://localhost:5001/api/project/getbyuser/string

### Alterar project
PUT https://localhost:5001/api/project/update
Content-Type: application/json

{
    "Name" : "Teste",
    "User" :  "Raphael",
    "Company" : "TESTE",
    "Created" : "2021-09-30",
    "StartDate" : "2021-09-30",
    "EndDate" : "2021-09-30"
}

### Deletar project
DELETE https://localhost:5001/api/project/delete/5