### Cadastrar project
POST http://localhost:5001/api/project/create
Content-Type: application/json

{
    "Name" : "Project 1",
    "Company" : "Tenda",
    "StartDate" : "2021-09-30",
    "EndDate" : "2021-10-30",
    "UserId": 1
}


### Listar project
GET http://localhost:5001/api/project/list

### Buscar project pelo id
GET http://localhost:5001/api/project/getbyid/6

### Buscar project pelo id
GET http://localhost:5001/api/project/getbyuser/string

### Alterar project
PUT http://localhost:5001/api/project/update
Content-Type: application/json

{
    "Name" : "Teste",
    "User" :  "Raphael",
    "Company" : "TESTE",
    "Created" : "2021-09-30",
    "StartDate" : "2021-09-30",
    "EndDate" : "2021-09-30"
}

### Deletar project
DELETE http://localhost:5001/api/project/delete/5