### Cadastrar project
POST https://localhost:5001/api/project/create
Content-Type: application/json

{
    "Name" : "Project 1",
    "User" : "Maria",
    "Company" : "Tenda",
    "StartDate" : "2021-09-30",
    "EndDate" : "2021-10-30"
}

### Listar project
GET https://localhost:5001/api/project/list

### Buscar project pelo id
GET https://localhost:5001/api/project/getbyid/1

### Alterar project
PUT https://localhost:5001/api/project/update
Content-Type: application/json

{
    "id" : 1,
    "Name" : "Project 1",
    "User" : "Maria",
    "Company" : "Tenda"
}

### Deletar project
DELETE https://localhost:5001/api/project/delete/Bolacha