### Cadastrar subtask
POST https://localhost:5001/api/subtask/create
Content-Type: application/json

{
    "Description" : "Task1",
    "TaskId" : 1,
    "End":false
}

### Listar subtasks
GET https://localhost:5001/api/subtask/list

### Buscar subtasks pelo id
GET https://localhost:5001/api/subtask/getbyid/1

### Alterar subtasks
PUT https://localhost:5001/api/subtask/update
Content-Type: application/json

{
    "id" : 1,
    "Description" : "Task2",
    "End":false
}

### Deletar subtasks
DELETE https://localhost:5001/api/subtask/delete/1