### Cadastrar user
POST https://localhost:5001/api/user/create
Content-Type: application/json

{
    "Name" : "Maria",
    "Office" : "DB1",
    "Company" : "Tenda"
}

### Listar user
GET https://localhost:5001/api/user/list

### Buscar user pelo id
GET https://localhost:5001/api/user/getbyid/1

### Alterar user
PUT https://localhost:5001/api/user/update
Content-Type: application/json

{
    "id" : 6,
    "Name" : "Maria",
    "Office" : "DB2",
    "Company" : "Tenda"
}

### Deletar user
DELETE https://localhost:5001/api/user/delete/7